AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ImageService

Parameters:

  StageEnv:
    Type: String
    Default: staging
    AllowedValues:
      - test
      - development
      - staging
      - production

Resources:

  ImageServiceLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lib/image_service.handler
      Runtime: ruby2.7
      Timeout: 60
      MemorySize: 512
      FunctionName: !Sub image-service-${StageEnv}
      Environment:
        Variables:
          STAGE_ENV: !Ref StageEnv
          RUBYOPT: '-W0'
      Events:
        ImageServiceS3BucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageServiceS3Bucket
            Events: s3:ObjectCreated:*
      Layers:
        - arn:aws:lambda:us-east-1:589405201853:layer:rubyvips892-27:13
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource:
                - !Sub arn:aws:s3:::image-service-thanh-12122020-${StageEnv}
                - !Sub arn:aws:s3:::image-service-thanh-12122020-${StageEnv}/*
  ImageServiceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub image-service-thanh-12122020-${StageEnv}

Outputs:

  ImageServiceLambdaArn:
    Description: Lambda Function Arn
    Value: !GetAtt ImageServiceLambda.Arn

